# Generated by Django 4.2.5 on 2023-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_done',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
