# Generated by Django 4.2.5 on 2023-10-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500)),
                ('answer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.answer')),
            ],
        ),
    ]
